/* Placeholder .pnp.loader.mjs
 * ESM loader helper for Yarn PnP. Generated by `yarn install`.
 * Run `yarn install` to create the actual loader file.
 */

export default function pnpLoader() {
  throw new Error('The real .pnp.loader.mjs is missing. Run `yarn install` to generate it.');
}
