/* Placeholder .pnp.cjs
 * This project is configured to use Yarn Plug'n'Play (PnP).
 * The actual .pnp.cjs is generated by running `yarn install`.
 * Keep this placeholder to avoid missing-file errors; run `yarn install` to generate the real file.
 */

module.exports = (function () {
  throw new Error('The real .pnp.cjs is missing. Run `yarn install` to generate it.');
})();
